// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LiberdadeDbContext))]
    partial class LiberdadeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Core.Entities.Ativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualDeRetornoMensalEsperado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RendimentoValorMesAnterior")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Core.Entities.MetaAlocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroFase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentualAlvo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetaAlocacoes");
                });

            modelBuilder.Entity("Core.Entities.PosicaoCarteira", b =>
                {
                    b.Property<Guid>("AtivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoAtual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.HasKey("AtivoId");

                    b.ToTable("PosicaoCarteiras");
                });

            modelBuilder.Entity("Core.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AtivoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("Core.Entities.Transacao", b =>
                {
                    b.HasOne("Core.Entities.Ativo", "Ativo")
                        .WithMany()
                        .HasForeignKey("AtivoId");

                    b.Navigation("Ativo");
                });
#pragma warning restore 612, 618
        }
    }
}
